### ISSUE TITLE
关于『与其“长途跋涉”地与输入的词向量配对，倒不如直接跟LSTM的中间状态向量配对』

### ISSUE THREAD

**Issue by cnkuangshi** [bojone/CCL_CMRC2017#1]
是采用W2V初始化词向量，训练两个双向RNN的损失目标是用RNN预测的下一个词向量，与上下文汇集而成的段落向量的交叉熵，是这样么

**Comment by bojone** [comment]
训练双向RNN是为了对上下文进行编码，然后再将全局编码（由上下文编码求平均得到）与每一个词的状态向量（最后一层双向RNN）做内积，然后就可以softmax预测概率了，最后loss是交叉熵。

**Comment by cnkuangshi** [comment]
我困惑的就是每个词的状态向量是什么，RNN每个输出么？上下文编码是只用最后一个神经元的输出么？做交叉熵描述的是上下文语意和什么的相关性？

**Comment by bojone** [comment]
@cnkuangshi 每个词的状态向量就是RNN的每个输出。上下文编码就是用最后一个时间步的输出，然后求平均得到全局编码。然后全局编码与RNN的每个输出做内积，然后softmax。介绍文章已经说了，说白了就是做语言模型的思路。
